datamodule:
  class: pkg.data.datamodules.ADNIDataModule
  args:
    data:
      data_dir: /project/aereditato/cestari/adni-mri-classification/data/preprocessing_multimodal/data/
      scan_csv: /project/aereditato/cestari/adni-mri-classification/data/preprocessing_multimodal/csv/dataset_multimodal.csv
      diagnostic_csv: /project/aereditato/cestari/adni-mri-classification/data/preprocessing_multimodal/csv/DXSUM_02Feb2026.csv
      diagnosis: [1,2,3]
      tolerance: 180
      modalities:
        MRI: ["MRI-T1-3T", "MRI-T1-1.5T"]
        PET: ["PET-FDG"]
    split:
      mode: kfold
      seed: 42
      folds: 5
      test_size: 0.1
      val_size: 0.2
    loader:
      batch_size: 4
      weighted_sampling: true
    transform:
      - random_flip:
          p: 0.5
      - random_affine:
          p: 0.5
          degrees: 5
          translation: 5
      - random_noise:
          p: 0.2
          std: 0.02

model:
  class: pkg.models.model_resnet18.ResNet18
  args:
    cfg:
      init_filters: 8
      dropout: 0.3
      num_classes: 3

optimizer:
  name: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.01

criterion:
  name: CrossEntropyLoss
  weights: auto
  params: {}
        
task:
  class: pkg.tasks.dummytask.DummyTask
  args: {}
    
trainer:
  max_epochs: 10

callbacks:
  - class: pkg.callbacks.metrics.Metrics
    args: {}

  - class: pkg.callbacks.checkpoint.CheckpointManager
    args: 
      monitor: val/loss
      mode: min 
      patience: 10

  - class: pkg.callbacks.scheduler.SchedulerPolicy
    args: 
      name: ReduceLROnPlateau
      params: {}





 



  
        