model:
  name: resnet14
  num_classes: 3
  in_channels: 1
  init_filters: 4

training:
  batch_size: 8
  epochs: 100
  optimizer:
    name: 'adam'
    weight_decay: 1e-4
    lr: 1e-3
  scheduler:
    name: 'CosineAnnealingLR'
    t_max: 100
    lr_max: 1e-3
    lr_min: 2e-6

data:
  trainval_csv: '/project/aereditato/cestari/adni-mri-classification/data/preprocessing_dicom_spm_2/data/trainval.csv'     
  test_csv: '/project/aereditato/cestari/adni-mri-classification/data/preprocessing_dicom_spm_2/data/test.csv'    
  augmentation: {}
    random_crop:
      p: 0.3
      min_scale: 0.9

cross_validation:
  method: holdout
  val_fraction: 0.2